CXX = mpiicpc
# the build target executable:
all: dust_simulation

dust_simulation : main.cpp world.cpp dustlist.cpp dustgrain.cpp randomgen.cpp parameterReader.cpp timer.cpp 
	$(CXX) -g -O0 -o dust_simulation main.cpp world.cpp dustlist.cpp dustgrain.cpp randomgen.cpp parameterReader.cpp timer.cpp

clean:
	-rm dust_simulation 

