# the compiler: gcc for C program, define as g++ for C++
CC = g++

  # compiler flags:
  #  -g    adds debugging information to the executable file
  #  -Wall turns on most, but not all, compiler warnings
CFLAGS  = -g -Wall -std=c++11

OBJS = main.o world.o dustlist.o dustgrain.o randomgen.o parameterReader.o

  # the build target executable:
all: dust_simulation main.o world.o dustlist.o dustgrain.o randomgen.o parameterReader.o

dust_simulation : ${OBJS}
	$(CC) $(CFLAGS) -o $@ ${OBJS}

main : main.cpp world.cpp dustlist.cpp parameterReader.cpp
	$(CC) $(CFLAGS) -o $@ $?

world : world.cpp dustlist.cpp
	$(CC) $(CFLAGS) -o $@ $?

dustlist : dustlist.cpp dustgrain.cpp randomgen.cpp
	$(CC) $(CFLAGS) -o $@ $?

dustgrain : dustgrain.cpp
	$(CC) $(CFLAGS) -o $@ $?

randomgen : randomgen.cpp
	$(CC) $(CFLAGS) -o $@ $?
	
parameterReader : parameterReader.cpp
	$(CC) $(CFLAGS) -o $@ $?
	
clean:
	$(RM) $(TARGET)
